# Form implementation generated from reading ui file 'edittask.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditTaskDialog(object):
    def setupUi(self, EditTaskDialog):
        EditTaskDialog.setObjectName("EditTaskDialog")
        EditTaskDialog.resize(389, 216)
        self.gridLayout = QtWidgets.QGridLayout(EditTaskDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelTaskSummary = QtWidgets.QLabel(EditTaskDialog)
        self.labelTaskSummary.setObjectName("labelTaskSummary")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelTaskSummary)
        self.lineEditSummary = QtWidgets.QLineEdit(EditTaskDialog)
        self.lineEditSummary.setObjectName("lineEditSummary")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditSummary)
        self.labelTag = QtWidgets.QLabel(EditTaskDialog)
        self.labelTag.setObjectName("labelTag")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelTag)
        self.comboBoxTags = QtWidgets.QComboBox(EditTaskDialog)
        self.comboBoxTags.setEditable(True)
        self.comboBoxTags.setObjectName("comboBoxTags")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxTags)
        self.labelDue = QtWidgets.QLabel(EditTaskDialog)
        self.labelDue.setObjectName("labelDue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDue)
        self.dateEdit = QtWidgets.QDateEdit(EditTaskDialog)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit)
        self.checkBoxEnableCalendar = QtWidgets.QCheckBox(EditTaskDialog)
        self.checkBoxEnableCalendar.setObjectName("checkBoxEnableCalendar")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBoxEnableCalendar)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.pushButtonDelete = QtWidgets.QPushButton(EditTaskDialog)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayoutButtons.addWidget(self.pushButtonDelete)
        self.pushButtonSave = QtWidgets.QPushButton(EditTaskDialog)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayoutButtons.addWidget(self.pushButtonSave)
        self.pushButtonCancel = QtWidgets.QPushButton(EditTaskDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayoutButtons.addWidget(self.pushButtonCancel)
        self.gridLayout.addLayout(self.horizontalLayoutButtons, 1, 0, 1, 1)

        self.retranslateUi(EditTaskDialog)
        QtCore.QMetaObject.connectSlotsByName(EditTaskDialog)

    def retranslateUi(self, EditTaskDialog):
        _translate = QtCore.QCoreApplication.translate
        EditTaskDialog.setWindowTitle(_translate("EditTaskDialog", "Dialog"))
        self.labelTaskSummary.setText(_translate("EditTaskDialog", "Task Summary"))
        self.labelTag.setText(_translate("EditTaskDialog", "Tag"))
        self.labelDue.setText(_translate("EditTaskDialog", "Due Date"))
        self.checkBoxEnableCalendar.setText(_translate("EditTaskDialog", "Enable Due Date"))
        self.pushButtonDelete.setText(_translate("EditTaskDialog", "Delete"))
        self.pushButtonSave.setText(_translate("EditTaskDialog", "Save"))
        self.pushButtonCancel.setText(_translate("EditTaskDialog", "Cancel"))
