# Form implementation generated from reading ui file 'multipurposeDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MultipurposeDialog(object):
    def setupUi(self, MultipurposeDialog):
        MultipurposeDialog.setObjectName("MultipurposeDialog")
        MultipurposeDialog.resize(420, 230)
        MultipurposeDialog.setMinimumSize(QtCore.QSize(420, 169))
        self.gridLayout = QtWidgets.QGridLayout(MultipurposeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.descriptionLabel = QtWidgets.QLabel(parent=MultipurposeDialog)
        self.descriptionLabel.setMinimumSize(QtCore.QSize(420, 150))
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=MultipurposeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=MultipurposeDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(MultipurposeDialog)
        self.buttonBox.accepted.connect(MultipurposeDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(MultipurposeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MultipurposeDialog)

    def retranslateUi(self, MultipurposeDialog):
        _translate = QtCore.QCoreApplication.translate
        MultipurposeDialog.setWindowTitle(_translate("MultipurposeDialog", "Dialog"))
        self.descriptionLabel.setText(_translate("MultipurposeDialog", "TextLabel"))
        self.label.setText(_translate("MultipurposeDialog", "Uh oh..........."))
